# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in calorie_tracker.gemspec


gem "rake", "~> 13.0"

gem "rubocop", "~> 1.7"

gem "rspec", "~> 3.10"

gem "colorizer", "~> 0.0.2"

# gem "require_all", "~> 3.0"
